apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    name: pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default 
  volumeMode: Filesystem 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /opt/nfs
    server: 34.85.194.232
    readOnly: false 
